# Generated by Django 4.2 on 2024-10-30 11:07

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GameMove',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('move', models.CharField(max_length=255)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='GameSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField(blank=True, null=True)),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('player1_points', models.IntegerField(default=0)),
                ('player2_points', models.IntegerField(default=0)),
                ('win_number', models.IntegerField(default=3)),
                ('move_speed_ball', models.IntegerField(default=6, validators=[django.core.validators.MaxValueValidator(10)])),
                ('move_speed_paddle', models.IntegerField(default=4, validators=[django.core.validators.MaxValueValidator(10)])),
                ('power', models.BooleanField(blank=True, null=True)),
                ('Multiplayer', models.BooleanField(blank=True, null=True)),
                ('bot', models.BooleanField(blank=True, null=True)),
                ('bot_difficulty', models.IntegerField(default=5, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
                ('player1_started', models.BooleanField(default=False)),
                ('player2_started', models.BooleanField(default=False)),
                ('player1', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='player1_sessions', to=settings.AUTH_USER_MODEL)),
                ('player2', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='player2_sessions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
