# Generated by Django 4.2 on 2024-11-05 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gamesession',
            name='win_number',
            field=models.IntegerField(default=5),
        ),
    ]
