# Generated by Django 4.2 on 2024-08-29 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_alter_gamesession_player2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamesession',
            name='player1_points',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='gamesession',
            name='player2_points',
            field=models.IntegerField(default=0),
        ),
    ]
