# Generated by Django 4.2 on 2024-09-06 06:51

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0003_gamesession_player1_points_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamesession',
            name='bot',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='gamesession',
            name='bot_difficulty',
            field=models.IntegerField(default=5, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)]),
        ),
        migrations.AddField(
            model_name='gamesession',
            name='move_speed_ball',
            field=models.IntegerField(default=6, validators=[django.core.validators.MaxValueValidator(10)]),
        ),
        migrations.AddField(
            model_name='gamesession',
            name='move_speed_paddle',
            field=models.IntegerField(default=4, validators=[django.core.validators.MaxValueValidator(10)]),
        ),
        migrations.AddField(
            model_name='gamesession',
            name='power',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='gamesession',
            name='win_number',
            field=models.IntegerField(default=3),
        ),
    ]
