# Generated by Django 4.2 on 2024-10-21 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0005_gamesession_player1_started_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamesession',
            name='Multiplayer',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
