# Generated by Django 4.2 on 2024-10-10 12:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('game', '0005_gamesession_player1_started_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gamesession',
            name='player1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='player1_sessions', to=settings.AUTH_USER_MODEL),
        ),
    ]
