# Generated by Django 4.2 on 2024-10-29 10:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0006_gamesession_multiplayer'),
        ('game', '0007_gamesession_tour'),
    ]

    operations = [
    ]
