services:
  db:
    container_name: database
    image: postgres:13
    restart: always
    environment:
      POSTGRES_DB: your_database_name
      POSTGRES_USER: your_database_user
      POSTGRES_PASSWORD: your_password
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - django_network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER}"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    container_name: redis
    image: redis:alpine  
    restart: always
    ports:
      - "6379:6379"
    networks:
      - django_network

  web:
    container_name: django
    image: django:transcendance
    build:
      context: ./website
      dockerfile: Dockerfile
    entrypoint: /app/entrypoint.sh
    command: daphne -b 0.0.0.0 -p 8000 transendence.asgi:application -v 2
    volumes:
      - ./website/srcs:/app/srcs
      - ./blockchain/srcs:/app/blockchain_v
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy
      redis:  # Dépendance à Redis ajoutée
        condition: service_started
    environment:
      - DB_NAME=your_database_name
      - DB_USER=your_database_user
      - DB_PASSWORD=your_password
      - DB_HOST=db
      - DB_PORT=5432
      - REDIS_HOST=redis  # Ajout de l'environnement pour Redis
    networks:
      - django_network

  bot:
    container_name: bot
    image: bot:transcendance
    build:
      context: ./AI
      dockerfile: Dockerfile
    networks:
      - django_network
    ports:
      - "8081:8081"

  pong:
    container_name: pong
    image: pong:transcendance
    build:
      context: ./pong 
      dockerfile: ./Dockerfile
    volumes:
      - ./pong:/app
    ports:
      - "8080:8080"
    networks:
      - django_network

  blockchain:
    container_name: ganache
    image: blockchain:transcendance
    build:
      context: ./blockchain
      dockerfile: dockerfile
    networks:
      - django_network
    ports:
      - "8545:8545"
    volumes:
      - ./blockchain/volumes:/app/volumes

networks:
  django_network:

volumes:
  postgres_data:
