# Generated by Django 4.2 on 2024-10-11 08:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0006_alter_gamesession_player1'),
        ('messaging', '0002_alter_message_conversation'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='invitation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='game.gamesession'),
        ),
    ]
