# Generated by Django 4.2 on 2024-10-17 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0003_message_invitation'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='is_tour',
            field=models.BooleanField(default=False),
        ),
    ]
