# Generated by Django 4.2 on 2024-10-17 11:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0003_remove_tournament_participants_and_more'),
        ('messaging', '0004_conversation_is_tour'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='conversation',
            name='is_tour',
        ),
        migrations.AddField(
            model_name='conversation',
            name='tour',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tournaments.tournament'),
        ),
    ]
