FROM node:14

RUN apt-get update && \
    apt-get install -y curl software-properties-common python3 python3-pip && \
    npm install -g ganache-cli

#Une erreur avec les nouvelles versions de ethers fais bugger le provider
RUN	npm install ethers@5.7.2

COPY srcs/ /app/sources/
EXPOSE 8545

 CMD ["sh", "-c", "ganache-cli -m 'potato blush range blue exchange naive replace output easy tiger bottom cupboard' --host 0.0.0.0 --port 8545 & sleep 2 && node /app/sources/deploy.js"]