# Utiliser une image de base Python
FROM python:3.9

# Installer les dépendances système nécessaires pour compiler les paquets Python
RUN apt-get update && apt-get install -y \
    build-essential \
    libpq-dev \
    libjpeg-dev \
    zlib1g-dev \
    gcc \
    python3-dev \
    musl-dev \
    --no-install-recommends \
    && rm -rf /var/lib/apt/lists/*

# Définir le répertoire de travail dans le conteneur
WORKDIR /app

# Copier le fichier de dépendances dans le conteneur
COPY requirements.txt .
COPY entrypoint.sh .

# Installer les dépendances Python
RUN pip install --no-cache-dir -r requirements.txt

# Copier tout le contenu du projet dans le conteneur
COPY srcs/ .
# COPY ./entrypoint.sh .
RUN chmod +x entrypoint.sh

# Exposer le port sur lequel l'application s'exécutera
EXPOSE 8000

# Utiliser le script d'entrée pour démarrer l'application
ENTRYPOINT ["./entrypoint.sh"]

# Commande pour démarrer l'application
# CMD ["python", "manage.py", "runserver", "0.0.0.0:8000"]
CMD ["uvicorn", "transcendence.asgi:application", "--host", "0.0.0.0", "--port", "8000"]
