# Utiliser l'image officielle de Nginx basée sur Alpine
FROM nginx:alpine

COPY nginx.conf /etc/nginx/conf.d/default.conf
COPY mycert.crt /etc/ssl/certs/mycert.crt
COPY mykey.key /etc/ssl/private/mykey.key
