# Utiliser l'image officielle de Nginx basée sur Alpine
FROM nginx:alpine

# Copier le fichier de configuration Nginx
COPY nginx.conf /etc/nginx/conf.d/default.conf

# Copier les certificats SSL
COPY mycert.crt /etc/ssl/certs/mycert.crt
COPY mykey.key /etc/ssl/private/mykey.key

# Les fichiers statiques seront disponibles dans le volume partagé
