# Utiliser une image de base Python
FROM python:3.9

# Installer les dépendances système nécessaires pour compiler les paquets Python
RUN apt-get update && apt-get install -y \
    build-essential \
    libpq-dev \
    libjpeg-dev \
    zlib1g-dev \
    gcc \
    python3-dev \
    musl-dev \
    --no-install-recommends \
    && rm -rf /var/lib/apt/lists/*

# Définir le répertoire de travail dans le conteneur
WORKDIR /app

# Copier les fichiers de dépendances et d'entrée dans le conteneur
COPY ./requirements.txt /app/
COPY ./entrypoint.sh /app/

# Installer les dépendances Python
RUN pip install --no-cache-dir -r requirements.txt && \
    pip install python-decouple

# Copier tout le contenu du projet dans le conteneur
COPY ./srcs /app/srcs

# Rendre le script d'entrée exécutable
RUN chmod +x /app/entrypoint.sh

# Exposer le port sur lequel l'application s'exécutera
EXPOSE 8000

# Utiliser le script d'entrée pour démarrer l'application
ENTRYPOINT ["/app/entrypoint.sh"]

# Commande pour démarrer l'application
CMD ["daphne", "-b", "0.0.0.0", "-p", "8000", "transendence.asgi:application", "-v", "2"]
