# Utiliser l'image Nginx officielle comme base
FROM nginx:alpine

# Copier les fichiers de votre application dans le répertoire Nginx
COPY . /usr/share/nginx/html

# Exposer le port que Nginx utilisera
EXPOSE 80
